services:
  - type: web
    name: lost-and-found-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/app-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true
